"use client";

import { type FormEvent, useState } from "react";
import { ContactApiError, submitContactRequest } from "@/services/contactApi";
import { type ContactRequest, projectTypes } from "@/types/contact";

const initialForm: ContactRequest = { name: "", email: "", company: "", phone: "", projectType: "", message: "" };
const fieldClass = "focus-ring mt-2 w-full rounded-xl border border-line bg-white px-4 py-3 text-ink placeholder:text-slate-400";

export function ContactForm() {
  const [form, setForm] = useState(initialForm); const [status, setStatus] = useState<"idle"|"sending"|"success"|"error">("idle"); const [error, setError] = useState("");
  const update = (field: keyof ContactRequest, value: string) => setForm((current) => ({ ...current, [field]: value }));
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("sending"); setError(""); try { await submitContactRequest(form); setStatus("success"); setForm(initialForm); } catch (cause) { setStatus("error"); setError(cause instanceof ContactApiError ? cause.message : "Something went wrong. Please try again."); } }
  if (status === "success") return <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-8" role="status"><h3 className="text-xl font-semibold text-emerald-900">Thanks for reaching out.</h3><p className="mt-3 text-emerald-800">Your request has been received. We’ll follow up using the email you provided.</p><button className="focus-ring mt-6 rounded-lg font-semibold text-emerald-900" onClick={() => setStatus("idle")}>Send another message</button></div>;
  return <form onSubmit={handleSubmit} className="rounded-3xl border border-line bg-white p-6 shadow-card sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">Name *<input className={fieldClass} required maxLength={120} autoComplete="name" value={form.name} onChange={(e)=>update("name",e.target.value)}/></label><label className="text-sm font-semibold">Email *<input className={fieldClass} required type="email" maxLength={254} autoComplete="email" value={form.email} onChange={(e)=>update("email",e.target.value)}/></label><label className="text-sm font-semibold">Company<input className={fieldClass} maxLength={160} autoComplete="organization" value={form.company} onChange={(e)=>update("company",e.target.value)}/></label><label className="text-sm font-semibold">Phone <span className="font-normal text-muted">(optional)</span><input className={fieldClass} type="tel" maxLength={40} autoComplete="tel" value={form.phone} onChange={(e)=>update("phone",e.target.value)}/></label><label className="text-sm font-semibold sm:col-span-2">Project type *<select className={fieldClass} required value={form.projectType} onChange={(e)=>update("projectType",e.target.value)}><option value="" disabled>Select a project type</option>{projectTypes.map((type)=><option key={type}>{type}</option>)}</select></label><label className="text-sm font-semibold sm:col-span-2">Message *<textarea className={`${fieldClass} min-h-36 resize-y`} required minLength={10} maxLength={5000} placeholder="What are you looking to build, improve, or automate?" value={form.message} onChange={(e)=>update("message",e.target.value)}/></label></div>{status === "error" && <p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>}<button type="submit" disabled={status === "sending"} className="focus-ring mt-6 w-full rounded-full bg-brand-600 px-6 py-3.5 font-semibold text-white shadow-lg shadow-brand-600/20 transition hover:bg-brand-700 disabled:cursor-wait disabled:opacity-70">{status === "sending" ? "Sending…" : "Start a Conversation"}</button><p className="mt-4 text-center text-xs leading-5 text-muted">Your details are used only to respond to this inquiry.</p></form>;
}
